# Generated by Django 3.2.11 on 2023-07-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_srudentresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SrudentResult',
            new_name='StudentResult',
        ),
    ]
